### ISSUE TITLE
Fails to install from PIP

### ISSUE THREAD

**Issue by trashcan** [v2e4lisp/termcolor2#1]
```
# pip install termcolor2
Password:
Downloading/unpacking termcolor2
  Downloading termcolor2-0.0.2.tar.gz
  Running setup.py (path:/private/tmp/pip_build_root/termcolor2/setup.py) egg_info for package termcolor2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/tmp/pip_build_root/termcolor2/setup.py", line 14, in <module>
        long_description = readme(),
      File "/private/tmp/pip_build_root/termcolor2/setup.py", line 6, in readme
        with open("README.rst") as it:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/tmp/pip_build_root/termcolor2/setup.py", line 14, in <module>

    long_description = readme(),

  File "/private/tmp/pip_build_root/termcolor2/setup.py", line 6, in readme

    with open("README.rst") as it:

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/termcolor2
Storing debug log for failure in /Users/<snip>/Library/Logs/pip.log
```

This is on OSX 10.10. Let me know if I'm doing something obvious wrong.

**Comment by v2e4lisp** [comment]
Thanks for reporting this bug. I fixed it. You can try to install it again.

**Comment by trashcan** [comment]
Works perfectly, thanks!
